# Generated by Django 4.0 on 2023-04-05 02:08

import django.core.validators
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_admin_customuser_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='additional_information',
            field=models.TextField(blank=True, max_length=4096, null=True, verbose_name='Additional information'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='address1',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Address line 1'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='address2',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Address line 2'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cover_pic',
            field=models.ImageField(default='defaults/cover.jpeg', upload_to='cover_images/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Date of birth', null=True, verbose_name='Date of birth'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='disability_type',
            field=models.CharField(blank=True, choices=[], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='display_name',
            field=models.CharField(blank=True, help_text='Display name', max_length=50, verbose_name='Display name'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_authenticated',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_disable',
            field=models.BooleanField(choices=[(False, 'Not disabled'), (True, 'Disabled')], default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid international mobile number', regex='^\\+?1?\\d{9,15}$')], verbose_name='Mobile phone'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(default='defaults/profile.svg', upload_to='profile_images/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='signup_confirmation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='zip_code',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Postal code'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank='False', max_length=254, null='False', unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
