# Generated by Django 4.0 on 2023-04-05 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_additional_information_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='disability_type',
            field=models.CharField(blank=True, choices=[('blindness', 'Blindness'), ('deafness', 'Deafness'), ('physical', 'Physical'), ('mental', 'Mental'), ('visceral', 'Visceral'), ('other', 'Other')], max_length=100, null=True),
        ),
    ]
