# Generated by Django 4.0 on 2023-04-10 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_waitinglist_userfollowing'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='waitinglist',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='waitinglist',
            name='following_user_id',
        ),
        migrations.RemoveField(
            model_name='waitinglist',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='UserFollowing',
        ),
        migrations.DeleteModel(
            name='WaitingList',
        ),
    ]
