# Generated by Django 4.1 on 2023-09-05 04:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_alter_customuser_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_pic",
            field=models.ImageField(
                default="//www.gravatar.com/avatar", upload_to="profile_images/"
            ),
        ),
    ]
