# Generated by Django 4.0 on 2023-04-10 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0009_alter_waitinglist_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(blank=True, max_length=25, null=True)),
                ('lastName', models.CharField(blank=True, max_length=25, null=True)),
                ('headLine', models.CharField(blank=True, max_length=100, null=True)),
                ('education', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=20, null=True)),
                ('location', models.CharField(blank=True, max_length=40, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('CustomUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='accounts.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('issuing_org', models.CharField(blank=True, max_length=200, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('credential_id', models.CharField(blank=True, max_length=100, null=True)),
                ('CustoUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_license', to='accounts.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(blank=True, max_length=100, null=True)),
                ('degree', models.CharField(blank=True, max_length=100, null=True)),
                ('field_of_study', models.CharField(blank=True, max_length=100, null=True)),
                ('start_year', models.CharField(blank=True, max_length=4, null=True)),
                ('end_year', models.CharField(blank=True, max_length=4, null=True)),
                ('CustomUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_education', to='accounts.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(blank=True, max_length=2000, null=True)),
                ('CustoUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_about', to='accounts.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(blank=True, max_length=100, null=True)),
                ('CustomUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_skills', to='accounts.customuser')),
            ],
            options={
                'unique_together': {('CustomUser', 'skill')},
            },
        ),
    ]
