# Generated by Django 4.0 on 2023-04-11 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0002_alter_profile_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='CustoUser',
            new_name='CustomUser',
        ),
    ]
